name: Test Project Structure Report

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "20"

            - name: Install Dependencies
              run: |
                  npm install
                  npm rebuild tree-sitter

            - name: Setup Test Projects
              run: |
                  mkdir -p sample-js-project
                  mkdir -p sample-python-project
                  mkdir -p sample-ts-project
                  echo "class SampleClass { test() {} }" > sample-js-project/index.js
                  echo "class SampleClass:\n    def test(self):\n        pass" > sample-python-project/main.py
                  echo "class SampleClass { test() {} }" > sample-ts-project/index.ts
                  # Add package.json for JavaScript projects
                  echo '{"name": "sample-js-project", "version": "1.0.0"}' > sample-js-project/package.json
                  echo '{"name": "sample-ts-project", "version": "1.0.0"}' > sample-ts-project/package.json
                  # Add setup.py for Python project
                  echo "from setuptools import setup, find_packages

setup(
    name='sample-python-project',
    version='1.0.0',
    packages=find_packages(),
)" > sample-python-project/setup.py

            - name: Generate Report (Sample Projects Only)
              run: node index.js "sample-js-project,sample-python-project,sample-ts-project"

            - name: Verify Report Content
              run: |
                  if ! grep -q "## Package (js): \`sample-js-project\`" .github/copilot-instructions.md; then
                    echo "Missing JavaScript project section"
                    exit 1
                  fi
                  if ! grep -q "## Package (py): \`sample-python-project\`" .github/copilot-instructions.md; then
                    echo "Missing Python project section"
                    exit 1
                  fi
                  if ! grep -q "## Package (js): \`sample-ts-project\`" .github/copilot-instructions.md; then
                    echo "Missing TypeScript project section"
                    exit 1
