name: Test Project Structure Report

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "20"

            - name: Install Dependencies
              run: |
                  npm install
                  npm rebuild tree-sitter

            - name: Generate Report (Full Repo)
              run: node index.js

            - name: Generate Report (Specific Paths)
              run: node index.js "src,test"

            - name: Verify Report
              run: |
                  if [ ! -f .github/copilot-instructions.md ]; then
                    echo "Report file not generated!"
                    exit 1
                  fi
